language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - python setup.py install

script:
    - python test/test_autopep8.py
    - python test/acid.py test/example.py

    - if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then python -m doctest -v README.rst; fi

    # Check that running tests in source distribution works.
    - python setup.py sdist --quiet --dist-dir=.tmp
    - cd .tmp
    - tar xf *.tar.gz
    - cd *
    - python setup.py test --quiet
