language: python

python:
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"
    - "pypy"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - python setup.py install

script:
    - python test/test_autopep8.py
    - python test/acid.py example.py --ignore=W602,E12
