language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - python setup.py --quiet install
    - pip install --quiet coveralls

before_script:
    # This is needed for Python multiprocessing.
    # https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

script:
    - python test/test_autopep8.py
    - python test/acid.py test/example.py

    - if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then python -m doctest -v README.rst; fi

    # Check that running tests in source distribution works.
    - python setup.py sdist --quiet --dist-dir=.tmp
    - cd .tmp
    - tar xf *.tar.gz
    - cd *
    - python setup.py test --quiet

    - if [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then pep8 autopep8.py; fi

    - coverage run --omit='*/virtualenv/*' test/test_autopep8.py

after_script:
    - coveralls
