language: python

python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.2"
    - "3.3"

install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - python setup.py install

script:
    - python test/test_autopep8.py
    - python test/acid.py test/example.py

    # Check that testing from source distribution works.
    - python setup.py sdist -d .tmp
    - cd .tmp
    - tar xf *.tar.gz
    - cd *
    - python setup.py test
